__author__ = 'Eduardo V. Sousa, Cristina N. Vasconcelos, Leandro A. F. Fernandes'
__author_email__ = 'eduardovera@ic.uff.br, crisnv@ic.uff.br, laffernandes@ic.uff.br'
__description__ = 'The implementation of the ConformalLayers'
__url__ = 'https://github.com/Prograf-UFF/ConformalLayers/'
__version__ = '1.2.1'
